network:
  version: 2
  ethernets:
    eth0:
      match:
        macaddress: xx:xx:xx:xx:xx:xx
      set-name: eth0
      dhcp4: false
      dhcp6: false
      accept-ra: false
      addresses: [10.194.1.2/24]
      routes:
        - to: 10.194.1.1/32
          on-link: true
        - to: 10.194.1.0/24
          on-link: true
          metric: 100
        - to: 0.0.0.0/0
          via: 10.194.1.1
      nameservers:
        search: [i.menhera.org]
        addresses: [1.1.1.1]
    eth1:
      match:
        macaddress: xx:xx:xx:xx:xx:xx
      set-name: eth1
      dhcp4: false
      dhcp6: false
      accept-ra: false
  bridges:
    br-moyo:
      interfaces: [eth1]
      dhcp4: false
      dhcp6: false
      accept-ra: false
      addresses: [10.194.1.3/24]
      routes:
        - to: 10.194.1.0/24
          on-link: true
          metric: 10
